# Generated by Django 5.0.8 on 2024-08-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=20)),
                ("user_password", models.CharField(max_length=255)),
                ("user_id", models.CharField(max_length=255, unique=True)),
                ("online_id", models.IntegerField(default=99, max_length=100)),
                ("user_email", models.EmailField(max_length=255)),
                (
                    "profile",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                ("api", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, verbose_name="last login"),
                ),
                ("is_authenticated", models.BooleanField(default=False)),
            ],
        ),
    ]
