# Generated by Django 5.0.8 on 2024-08-10 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMsetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "llm_category",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "deepseek"), (2, "gpt-4o"), (3, "gpt-3.5-turbo")],
                        default=1,
                    ),
                ),
                ("llm_api", models.CharField(default="添加模型 API", max_length=255)),
                ("llm_token", models.IntegerField(default=4096)),
                ("llm_temp", models.CharField(default="0.9", max_length=20)),
                (
                    "stage1",
                    models.TextField(
                        default="As a program analyst, I give you snippets of C code generated by decompilation, using {start} as the taint source, and {parameter} marked as the taint label to extract the taint data flow. Pay attention to the data alias and tainted data operations. Output in the form of data flows."
                    ),
                ),
                (
                    "stage2",
                    models.TextField(
                        default="Continue to analyze {function} according to the above taint analysis results. Pay attention to the data alias, tainted data operations, and sources."
                    ),
                ),
                (
                    "stage3",
                    models.TextField(
                        default="Based on the above taint analysis results, analyze whether the code has vulnerabilities. If there is a vulnerability, please explain what kind of vulnerability according to CWE. Think step by step."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=20)),
                ("user_password", models.CharField(max_length=255)),
                ("user_id", models.CharField(max_length=255, unique=True)),
                ("online_id", models.IntegerField(default=99)),
                ("user_email", models.EmailField(max_length=255)),
                (
                    "profile",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                ("api", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, verbose_name="last login"),
                ),
                ("is_authenticated", models.BooleanField(default=False)),
                (
                    "llm_model",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.llmsetting",
                    ),
                ),
            ],
        ),
    ]
