from django.db import models

# Create your models here.

class LLMsetting(models.Model):
    CATEGORY_CHOICES = [
        (1, 'deepseek'),
        (2, 'gpt-4o'),
        (3, 'gpt-3.5-turbo')
    ]
    llm_category = models.PositiveSmallIntegerField(choices=CATEGORY_CHOICES, default=1)  # LLM类别
    llm_api = models.CharField(max_length=255, default="添加模型 API")

    llm_token = models.IntegerField(default=4096)
    llm_temp = models.CharField(max_length=20, default="0.9")

    stage1 = models.TextField(default="As a program analyst, I give you snippets of C code generated by decompilation, using {start} as the taint source, and {parameter} marked as the taint label to extract the taint data flow. Pay attention to the data alias and tainted data operations. Output in the form of data flows.")
    stage2 = models.TextField(default="Continue to analyze {function} according to the above taint analysis results. Pay attention to the data alias, tainted data operations, and sources.")
    stage3 = models.TextField(default="Based on the above taint analysis results, analyze whether the code has vulnerabilities. If there is a vulnerability, please explain what kind of vulnerability according to CWE. Think step by step.")

class User(models.Model):

    user_name = models.CharField(max_length=20)
    user_password = models.CharField(max_length=255)
    user_id = models.CharField(max_length=255, unique=True)
    online_id = models.IntegerField(default=99)
    user_email = models.EmailField(max_length=255)
    profile = models.ImageField(upload_to='profile_pictures/', null=True, blank=True) #头像
    api = models.CharField(max_length=255)
    bio = models.TextField(max_length=500, blank=True,null=True) #Self-introduction
    last_login = models.DateTimeField(
        verbose_name='last login',
        auto_now=True
    )
    is_authenticated = models.BooleanField(default=False)

    llm_model = models.OneToOneField(LLMsetting, on_delete=models.CASCADE)

    def __str__(self):
        return self.user_name

